### PR TITLE
Add step to prepare input before parsing idl file

### PR DESCRIPTION
**Pull request by shnewto**
Prior to this commit this tool's parsing logic made assumptions about
whitespace inside array and sequence definitions. Due to these
assumptions the following scenarios broke the tool's ability
to correctly parse a legal OMG IDL file:

```
int array1[ 10 ];
int array2[
  10
  ];
sequence< int > seq1;
sequence<
  int
  > seq2;
```

Logic was added to prepare a file to meet the assumptions of
the parser before parsing. With regular expressions any whitespace
between brackets (including newlines) is eliminated.

Another assumption made by the parser was that arrays were defined
with integer constants. This resulted in the following scenario
breaking the tool's parsing ability:

```
const MY_CONSTANT = 10;

int array1[ MY_CONSTANT ];

```

After this commit the tool no longer makes the assumption that the
size of an array is defined by and integer constant. This resulted
in a modification of the code that cast the value to an `int` as
well as modifications to tests that asserted the value was an int
value. If this change is unacceptable I can revisit the logic and
try another approach.

I was also able to find certain scenarios that challenged the
assumptions I made about the refine_typename function in a
previous commit. Small changes to that function resolved the
issues I encountered.

Thank you for taking the time to review the changes I've proposed.

### CODE REVIEW

**Comment by sugarsweetrobotics** [comment]
@snewt Thank you very much for your great contribution. 
The situation when the array size is given as the constant variable was out of my thoughts.

But, actually I do not like this modification. This API forces the users to parse the string (both literal number or name of constant).

Currently, I am very open to modify the API dynamically (or even radically). 
Please give me your ideas.
My option is... how about adding the Literal class (like Const class), and both literal number and const number can be accessed the same (or similar) APIs.

**Comment by shnewto** [comment]
@sugarsweetrobotics thank you for your feedback, I agree with your concerns and have attempted to address them. For my uses I do not need the name of the constant used to define the size of an array, only the value. I have revised my approach to retrieve the literal value from the constant's name used to define the array size (see `idl_parser/type.py`). Please see my most recent commit message. 

If the recent changes do not fully address your concern I will revisit the code again. I explored the option of adding a `Literal` class but my preliminary implementation required other breaking changes and anyone currently using the tool to would have to revise their implementation. 

Again, thank you for taking the time to review my changes, I really like this tool and find a lot of value in it.

**Comment by shnewto** [comment]
~~hmm, the recent changes seems to have issues if there is no module specified. I'll address and push a change.~~ The parser now does not assume there are modules explicitly defined and is able to determine an array's defined size in either case.

**Comment by sugarsweetrobotics** [comment]
Thank you very much for your great contribution. This seems familiar to me.

**Pull request merged**
